name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 1466587594/get-current-time@v2
        id: current-time
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: dist
          path: dist
      - run: |
          rm -rf dist/*
          npm install
          npm run all
          cp action.yml dist/action.yml
      - run: |
          cd dist
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . --force
          git commit -m "Update ${{ steps.current-time.outputs.time }}"
          git tag -a -m "Update ${{ steps.current-time.outputs.time }}" v1
          git push --follow-tags
